spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lunch_roulette?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis-Plus configuration
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.lunchroulette.model
  configuration:
    map-underscore-to-camel-case: true

# JWT configuration
jwt:
  secret: lunchRouletteSecretKeyChangeMeInProductionEnvironment
  expiration: 86400000 # 24 hours in milliseconds

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

# CORS configuration
cors:
  allowed-origins: "http://localhost:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true